[package]
name = "cycler"
version = "0.1.0"
authors = ["buzzec <buzzec@buzzec.net"]
edition = "2018"

[dependencies]
parking_lot = { version = "0.11.1", features = ["send_guard"] }

[features]
default = []
unsafe_cleanup = []
